name: Cargo Build & Test

on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Build and test
    runs-on: ${{ matrix.os }}
    env:
      # Make warnings fatal
      RUSTFLAGS: -D warnings
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v5
      - name: Cargo Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
            target
          key: ${{ matrix.os }}-cargo-${{ hashFiles('Cargo.toml') }}
          restore-keys: |
            ${{ matrix.os }}-cargo-${{ hashFiles('Cargo.toml') }}
            ${{ matrix.os }}-cargo
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - run: cargo build --verbose
      - run: cargo test --verbose
